sudo: required

language: node_js
node_js: "10"

cache:
  directories:
    - node_modules

git:
  depth: 3

matrix:
  include:
    - name: "Build for Windows on Ubuntu"
      if: tag IS present
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
      before_install:
        - "travis_wait 30 sleep 1800 &"
        - sudo dpkg --add-architecture i386
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        - sudo apt-get install apt-transport-https ca-certificates
        - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        - wget -nc https://dl.winehq.org/wine-builds/winehq.key
        - sudo apt-key add winehq.key
        - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
        - sudo apt-get update -qy
        - sudo apt-get install -y mono-complete ca-certificates-mono
        - sudo apt-get install --install-recommends -y wine64-* winehq-stable
      install:
        - npm install
      script:
        - npm run build-win
      after_success:
        - curl --progress-bar --upload-file dist/Udeler*.exe https://transfer.sh/ && echo ""
    - name: "Build for Ubuntu"
      if: tag IS present
      os: linux
      dist: xenial
      addons:
        apt:
          update: true
      install:
        - npm install
      script:
        - "travis_wait 30 sleep 1800 &"
        - npm run build-linux
      after_success:
        - curl --progress-bar --upload-file dist/Udeler*.AppImage https://transfer.sh/ && echo ""
    - name: "Build for MacOS"
      if: tag IS present
      os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          update: true
      install:
        - npm install
      script:
        - "travis_wait 30 sleep 1800 &"
        - npm run build-mac
      after_success:
        - curl --progress-bar --upload-file dist/Udeler*.zip https://transfer.sh/ && echo ""
        - curl --progress-bar --upload-file dist/Udeler*.dmg https://transfer.sh/ && echo ""

branches:
  only:
    - updates
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file:
    - dist/Udeler*.AppImage
    - dist/Udeler*.exe
    - dist/Udeler*.dmg
    - dist/Udeler*.zip
  on:
    tags: true
    branch: updates
