sudo: required

language: node_js
node_js: "10"

cache:
  directories:
    - node_modules

git:
  depth: 3

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        - sudo apt install apt-transport-https ca-certificates
        - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        - sudo apt update -q
        - sudo apt install -y mono-devel ca-certificates-mono
        - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        - sudo apt update -q
        - sudo apt install --install-recommends -y wine64
      install:
        - npm install
      script:
        - npm run build-win
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
      install:
        - npm install
      script:
        - npm run build-linux
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          update: true
      install:
        - npm install
      script:
        - npm run build-mac

branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_deploy:
  - git config --local user.name "fr3aky"
  - git config --local user.email "fr3aky@phantom.zone"
  - export TRAVIS_TAG=${TRAVIS_TAG:-Udeler-Snapshot-$(date +'%Y%m%d')}
  - git tag $TRAVIS_TAG

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file:
    - dist/Udeler*.AppImage
    - dist/Udeler*.exe
    - dist/Udeler*.dmg
