sudo: required

language: node_js
node_js: "10"

cache:
  directories:
    - node_modules

git:
  depth: 3

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        - sudo apt-get install apt-transport-https ca-certificates
        - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        - sudo apt-get update -qy
        - sudo apt install -y mono-complete ca-certificates-mono
        - wget -nc https://dl.winehq.org/wine-builds/winehq.key
        - sudo apt-key add winehq.key
        - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
        - sudo apt-get update -qy
        # - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        # - sudo apt-get update -qy
        - sudo apt-get install --install-recommends -y wine64-* winehq-stable
      install:
        - npm install
      script:
        - npm run build-win
      after_success:
        - curl --progress-bar --upload-file dist/Udeler*.exe https://file.io/?expires=14d && echo ""
        - curl --progress-bar --upload-file dist/Udeler*.exe https://0x0.st/ && echo ""
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
      install:
        - npm install
      script:
        - npm run build-linux
      after_success:
        - curl --progress-bar --upload-file dist/Udeler*.AppImage https://file.io/?expires=14d && echo ""
        - curl --progress-bar --upload-file dist/Udeler*.AppImage https://0x0.st/ && echo ""
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          update: true
      install:
        - npm install
      script:
        - npm run build-mac
      after_success:
        - curl --progress-bar --upload-file dist/Udeler*.zip https://file.io/?expires=14d && echo ""
        - curl --progress-bar --upload-file dist/Udeler*.dmg https://file.io/?expires=14d && echo ""
        - curl --progress-bar --upload-file dist/Udeler*.zip https://0x0.st/ && echo ""
        - curl --progress-bar --upload-file dist/Udeler*.dmg https://0x0.st/ && echo ""

branches:
  only:
    - updates
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
